version: '3'
services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=cH13F_c0mM4nD3r
      - MYSQL_DATABASE=complaints_db
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=cH13F_c0mM4nD3r

  complaints_server:
    container_name: complaints_server
    build: ./complaints_server/
    volumes:
      - ./complaints_server/public_html:/var/www/html
    depends_on:
      - db

  main_server:
    container_name: main_server
    build: ./main_server/
    command: bash -c "./init.sh"
    ports:
      - "80:80"
    volumes:
      - ./main_server/public_html:/var/www/soldier.io/public_html
    depends_on:
      - complaints_server
    tty: true
