version: '3'
services:
  users_db:
    image: mysql
    container_name: users_db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./users_db/scripts:/var/lib/mysql
      - ./users_db:/docker-entrypoint-initdb.d/
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=l33t_h4xx0r
      - MYSQL_DATABASE=l33t_db
      - MYSQL_USER=l33t_user
      - MYSQL_PASSWORD=l33t_h4xx0r

  main_server:
    container_name: main_server
    build: ./main_server/
    command: bash -c "./init.sh"
    ports:
      - "80:80"
    volumes:
      - ./main_server/public_html:/var/www/anything.com/public_html
    depends_on:
      - users_db
    tty: true
